version: 2.1
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    steps:
      - checkout
      - run: dotnet build
      - run: ls
      #- store_bin:
          #path:
workflows:
  build:
    jobs:
      - build
